### ISSUE TITLE
/bin/sh: g++-mp-4.8: command not found

### ISSUE THREAD

**Issue by omega1119** [nolanlab/Rclusterpp#5]
Hi there,

I'm trying to install Rclusterpp for R on my os x laptop. I have followed the installation instructions here: https://github.com/nolanlab/Rclusterpp/wiki/Getting-Started and when I try to run install.packages(c("Rcpp","RcppEigen","Rclusterpp"),type="source") in R, I keep getting the error /bin/sh: g++-mp-4.8: command not found. Any ideas on how to get around this?

Thanks,
Simon

**Comment by rbruggner** [comment]
Sounds like g++ isn't installed or visible in the execution path. Did you confirm that gcc48 is installed /  active on the command line?
