### ISSUE TITLE
occasional segfault with Rclusterpp.hclust 

### ISSUE THREAD

**Issue by pkimes** [nolanlab/Rclusterpp#6]
I'm running into segfault errors occasionally (maybe 1/10 times) when running `Rclusterpp.hclust`. Any idea why this might be occurring? 

I've uploaded a simple (simulated) data set where I run into a segfault as a gist for reference.
This data set only appears to cause a segfault with `method = "ward"`, but I've also observed segfaults with other linkages (e.g. `method = "complete"`) as well (for other data).

---
Printing out the sessionInfo.
```
 library(Rclusterpp)
 # Loading required package: Rcpp
 # Loading required package: RcppEigen
 
 sessionInfo()
 # R version 3.4.2 (2017-09-28)
 # Platform: x86_64-apple-darwin15.6.0 (64-bit)
 # Running under: OS X El Capitan 10.11.6
 # 
 # Matrix products: default
 # BLAS/LAPACK: /usr/local/Cellar/openblas/0.2.20/lib/libopenblasp-r0.2.20.dylib
 # 
 # locale:
 # [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
 # 
 # attached base packages:
 # [1] stats     graphics  grDevices utils     datasets  methods   base
 # 
 # other attached packages:
 # [1] Rclusterpp_0.2.3    RcppEigen_0.3.3.3.1 Rcpp_0.12.16
 # 
 # loaded via a namespace (and not attached):
 # [1] compiler_3.4.2  Matrix_1.2-12   tools_3.4.2     grid_3.4.2
 # [5] lattice_0.20-35
```
The data can be loaded from the gist.
```
 dat <- read.table(paste0("https://gist.githubusercontent.com/pkimes/",
                          "9d84b603a3f856b100c33e67c7c477fd/raw/",
                          "079ab207f980edafbb893562c6f4ad9e9929338c/",
                          "testdata.txt"))
```
The standard `stats::hclust` appears fine.
```
 hclust(dist(dat), method = "ward.D2")
 # 
 # Call:
 # hclust(d = dist(dat), method = "ward.D2")
 # 
 # Cluster method   : ward.D2
 # Distance         : euclidean
 # Number of objects: 48
```
Unfortunately, I run into a segfault with `Rclusterpp.hclust`.
```
 Rclusterpp.hclust(dat)
 # 
 #  *** caught segfault ***
 # address 0x5, cause 'memory not mapped'
 # 
 # Traceback:
 #  1: .Call("hclust_from_data", data = x, link = as.integer(method),     dist = as.integer(distance), p = as.numeric(p), DUP = FALSE,     NAOK = FALSE, PACKAGE = "Rclusterpp")
 #  2: Rclusterpp.hclust(dat)
 # 
 # Possible actions:
 # 1: abort (with core dump, if enabled)
 # 2: normal R exit
 # 3: exit R without saving workspace
 # 4: exit R saving workspace
```

**Comment by pkimes** [comment]
@SamGG thanks for the quick reply!
I included the `sessionInfo` at the top of my example after loading `Rclusterpp`. (Unfortunately, because I get a segfault, I can't print the `sessionInfo` after calling `Rclusterpp.hclust`.) I'm running R-3.4.2.

I also tried updating RcppEigen to `RcppEigen_0.3.3.4.0` and am still getting the segfault. If you're not seeing the error, I guess this might be something with how my `Rcpp`/`RcppEigen` is setup?

**Comment by SamGG** [comment]
Hi Patrick,
This might be related to some Mac specificities. Unfortunately, I am not experienced with that environment. But you will get some help from the developers that are used to. Meanwhile you could maybe try the latest R 3.4.4.
Best.

**Comment by rbruggner** [comment]
Hi Patrick, 

In the past I've run into segfaults if Rcpp / RcppEigen / Rclusterpp are compiled using different versions of gcc / different compilers. Easiest way to remedy was usually just to reinstall those packages from source rather than use the CRAN binaries. 

```
R> library("devtools")
R> install.packages(c("Rcpp","RcppEigen"),type="source")
R> install_github("nolanlab/Rclusterpp")
```

LMK if that helps?

**Comment by pkimes** [comment]
Hi @rbruggner, thanks! I'll give this a try.
