### ISSUE TITLE
Package no longer on CRAN

### ISSUE THREAD

**Issue by bjw34032** [nolanlab/Rclusterpp#7]
FYI, this is the information I receive from CRAN

> Package ‘Rclusterpp’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the archive.
> 
> Archived on 2018-05-09 as check problems were not corrected despite reminders.

To install, should I use the last archived version or do you support installation directly from github via devtools::install_github()?

Thanks, Brandon

**Comment by rbruggner** [comment]
I recommend installing from github. The GitHub source has several bugs fixes implemented that are not in the cran version.

**Comment by bjw34032** [comment]
Cool, thanks!
